services:
  accounts:
    image: "vivekkarli/accounts:v1"
    container_name: accounts-ms
    ports:
      - 8080:8080
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - idealbank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod

  loans:
    image: "vivekkarli/loans:v1"
    container_name: loans-ms
    ports:
      - 8090:8090
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - idealbank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod

  cards:
    image: "vivekkarli/cards:v1"
    container_name: cards-ms
    ports:
      - 9000:9000
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - idealbank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: prod

  configserver:
    image: "vivekkarli/configserver:v1"
    container_name: configserver-ms
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 8071:8071
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - idealbank


networks:
  idealbank:
    driver: "bridge"